swagger: "2.0"
info:
  description: "Basic swagger description"
  version: "1.0.0"
  title: "Swagger Bulks Store"
host: "9aj51mlxlc.execute-api.eu-west-1.amazonaws.com"
basePath: "/dev"
tags:
  - name: "productService"
    description: "Provide product data"
paths:
  /products:
    get:
      tags:
        - "productService"
      summary: "Get product list"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/ProductsResponse"
        500:
          description: "Internal server error"
  /product:
    get:
      tags:
        - "productService"
      summary: "Get specific product"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "query"
          description: "Product id"
          required: false
          type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Product"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
    post:
      summary: "Create new product"
      parameters:
        - in: body
          name: "Product"
          description: "Product to create"
          schema:
            $ref: '#/definitions/Product'
      responses:
        201:
          description: "Product created"
        400:
          description: "Bad request"
        500:
          description: "Internal server error"
definitions:
  ProductsResponse:
    type: "array"
    items:
      $ref: "#/definitions/Product"
  Product:
    type: "object"
    properties:
      title:
        type: "string"
      description:
        type: "string"
      id:
        type: "string"
      price:
        type: "number"
      count:
        type: "integer"
